# Generated by Django 5.1.2 on 2024-10-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_remove_comment_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_on',
        ),
    ]
